### PR TITLE
Ac/pm 14415/add vs code extension cli option

### PR DESCRIPTION
**Pull request by JimmyVo16**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-14415

## 📔 Objective

Add a CLI option to install VS code extensions quickly. This uses the VS code executable, so no extra dependencies are needed.

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation
  team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed
  issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by JimmyVo16** [comment]
I know we’re no longer on BEEEP day, but I thought this would be a good opportunity to practice pushing MRs here, lol. I followed this doc and used Vince’s example [MR](https://github.com/bitwarden/contributing-docs/pull/456) as a guide.
Please let me know if there’s anything I should change. We can also move the feedback to the MR if that’s easier.

**Comment by withinfocus** [comment]
How can these tool installation commands map to the suggestions above this change? I think it would flow better if a CLI command was tied to that. You could also use the URL handler to launch these in the UI too, but the Marketplace site will also offer that so it may be moot.

**Comment by eliykat** [comment]
Thanks for adding to the documentation @JimmyVo16 !

vscode also supports "recommended extensions" for a workspace - see [the current list here](https://github.com/bitwarden/clients/blob/main/clients.code-workspace#L69-L76). Here's how it looks:

Screenshot 2024-11-05 at 9 50 00 AM

I think adding them in the workspace file would make them more discoverable and easier to add, and then you could mention this "recommended extensions" functionality in this document as well.

This can be done as well as or in addition to the CLI commands, I don't mind.

**Comment by JimmyVo16** [comment]
> How can these tool installation commands map to the suggestions above this change? I think it would flow better if a CLI command was tied to that. You could also use the URL handler to launch these in the UI too, but the Marketplace site will also offer that so it may be moot.

I envisioned a use case where a user might want to install all the extensions in one go. Instead of manually clicking through each extension individually, they could simply run this script. Like you mentioned, for cases where someone wants only specific extensions, the current format already accommodates that.

I don't think it's practical to try accounting for more granular cases, like installing half the extensions or specific subsets, because that would introduce significant complexity with the permutations involved.

**Comment by JimmyVo16** [comment]
> Thanks for adding to the documentation @JimmyVo16 !
> 
> vscode also supports "recommended extensions" for a workspace - see [the current list here](https://github.com/bitwarden/clients/blob/main/clients.code-workspace#L69-L76). Here's how it looks:
> 
> Screenshot 2024-11-05 at 9 50 00 AM
> 
> I think adding them in the workspace file would make them more discoverable and easier to add, and then you could mention this "recommended extensions" functionality in this document as well.
> 
> This can be done as well as or in addition to the CLI commands, your choice.

That's a great idea for the future! I believe the current PR brings value as it stands, so we should merge it and potentially revisit this option at a later time.

**Review by withinfocus — COMMENTED** [review]
I think Thomas has a valid point in just directing this to the recommended extension method, and this is backed up by the [VS Code documentation](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions). As-is this would create a second location to maintain the list, and while the recommendations probably should have been updated in the past it's good to have one place for it, now. Any number of things could have additional setup needs or even error out and one sequential script could obscure that feedback, whereas the UI makes that clear visually. The recommendation method also allows the user to pick and choose what they might want, and I would argue that we should just remove this entire list here in favor of that experience.

**Comment by JimmyVo16** [comment]
@withinfocus 

Those are valid points. I'll close this PR and add the extensions to the workspace.

**Pull request closed without merging**
